### ISSUE TITLE
Missing data error / lmtp package

### ISSUE THREAD

**Issue by MFosset** [kathoffman/steroids-trial-emulation#1]
Hi, 

When I run the analysis.R script, I end up with 

`Error in lmtp_sdr(dat_lmtp, trt = a, outcome = y, baseline = bs, time_vary = tv,  : 
  Assertion on 'data' failed: Missing data found in treatment and/or covariate nodes for uncensored observations.`

It occurs after I tried to define the res_steroid object with the lmtp_sdr function.

I have indeed a lot of missing data in the dat_lmtp file, but is it a problem of missing data or is the censoring variable that don't have the correct output ?

Thanks in advance

**Comment by kathoffman** [comment]
Thanks for catching this @MFosset! I just fixed this.

The error stemmed from a line of code naming the baseline covariates in the `bs` object. It incorrectly contained names of some time-varying covariates (`M_*`) that were indeed missing! I am now directly naming the baseline covariates for clarity.
